# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [2]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

height_np = np.array(height)
weight_np = np.array(weight)
bmi_calc = weight_np / (height_np **2) * 730

bmi_calc





array([16.86620458, 17.87755102, 18.82562984, 19.71450617, 20.54794521,
       21.32943755, 22.06222222])

### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [12]:
# Example makeMatrix(param1,param2) -- Extra params can be added here as well

# def makeMatrix(low,high,shape,data_type = float):
#     pass

# def makeRandom(low, high):
#     randomNum = np.random.uniform(low, high)
#     print(f'A matrix generated for a random number between {low} and {high} is: {randomNum}')

# makeRandom(1,75)




def makeRandom2(low, high, size, data_type):
    if data_type == int:
        random_arr = np.random.randint(low, high, size)
    else:
        random_arr = np.random.uniform(low, high, size)
    return random_arr        
    

print(makeRandom2(1,75,(3,5), float))


[[ 9.4051898  74.23475998  5.95418351 11.74312027 40.02800348]
 [30.73037238 21.16950122 63.57218503 31.63788077 61.44904394]
 [19.90494088 74.74336882 59.64001331 64.81348391 41.49257507]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [28]:
import csv
import numpy as np
from datetime import datetime
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

# to confirm data can be read
def open_csv(filename, d= ','):
    data = []
    with open(filename, encoding = 'utf-8') as mData:       
        info = csv.reader(mData, delimiter = d)       
        for row in info:
            data.append(row)
    return data

csv_data = open_csv('D:/Coding_Temple/week8/files/redsox_2017_hitting.csv')
#print(csv_data[1])

#Use this function to actually open the data inside of a NDArray

def load_data(filename, d=','):
    data = np.genfromtxt(filename, delimiter = d,skip_header = 1,
                        usecols= np.arange(0,24), invalid_raise = False,
                        names= FIELDS, dtype = DATATYPES)
    return data

#calculate higher avg SLG percentage
def betterYear():
    bs2017 = load_data('D:/Coding_Temple/week8/files/redsox_2017_hitting.csv')
    slg_2017 = bs2017['SLG']
    avg_slg_2017 = sum(bs2017['SLG']) / len(slg_2017)
    
    bs2018 = load_data('D:/Coding_Temple/week8/files/redsox_2018_hitting.csv')
    slg_2018 = bs2018['SLG']
    avg_slg_2018 = sum(bs2018['SLG']) / len(slg_2018)
    
    if avg_slg_2018 > avg_slg_2017:
        print(f'The avg SLG for the Boston Red Sox was better in 2018 at {avg_slg_2018}')
    else:
        print(f'The avg SLG for the Boston Red Sox was better in 2017 at {avg_slg_2017}')
    

betterYear()


The avg SLG for the Boston Red Sox was better in 2017 at 0.39334782374941785
